ERROR 2022-09-27 16:36:42,832 connection.py _on_error       266 Connection to remote host was lost.
